version: "3.8"
services:
  nginx:
    image: ebairachtari/nginx-custom:latest
    container_name: compose-nginx
    ports:
      - "8081:80" # Διαφορετική πόρτα για να μην έρχεται σε σύγκρουση
    # volumes:
    #  - ./nginx-data:/usr/share/nginx/html
    restart: always

  redis:
    image: ebairachtari/custom-redis:latest
    container_name: compose-redis
    ports:
      - "6380:6379" # Διαφορετική πόρτα για να μην έρχεται σε σύγκρουση
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:

