apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30079 # (Μπορείς να αφήσεις το Kubernetes να διαλέξει αυτόματα)
  selector:
    app: redis
